Catch up with docs moving to YARD
In 9437b34975867d111f0c7c1053a48e70cd193555.

Without these gemspec updates, the gem fails to be built with the
following error:

```
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["AUTHORS.rdoc", "CHANGELOG.rdoc", "COPYING.rdoc", "README.rdoc"] are not files
```